version: "3.8"

services:
  db:
    image: postgis/postgis
    container_name: walks_with_smalls_db_1
    volumes:
      - type: volume
        source: pg_data
        target: /var/lib/postgresql/data

  web:
    container_name: walks_with_smalls_web_1
    command: /bin/bash -c "pipenv run gunicorn core.wsgi"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONPATH=walks_with_smalls

volumes:
  pg_data:
