version: "3.8"

services:
  db:
    env_file:
      - .config/.env.dev
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    image: walks_with_smalls:dev
    command: /bin/bash -c "pipenv run python walks_with_smalls/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    env_file:
      - .config/.env.dev
