# Generated by Django 3.1.3 on 2020-11-12 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0003_walk"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="continent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="formatted",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="geohash",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="postcode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="reverse_geocode_cache_time",
            field=models.DateTimeField(
                default=datetime.datetime(2018, 11, 23, 14, 17, 5, 484076, tzinfo=utc)
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="road",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="suburb",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="what3words",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
