# Generated by Django 3.1.3 on 2020-11-13 20:37

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc
import walks.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("walks", "0004_auto_20201112_1417"),
    ]

    operations = [
        migrations.RemoveField(model_name="place", name="owner",),
        migrations.RemoveField(model_name="walk", name="owner",),
        migrations.AddField(
            model_name="place",
            name="submitter",
            field=models.ForeignKey(
                default=1,
                on_delete=models.SET(walks.models.get_sentinel_user),
                to="users.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="walk",
            name="submitter",
            field=models.ForeignKey(
                default=1,
                on_delete=models.SET(walks.models.get_sentinel_user),
                to="users.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="place",
            name="reverse_geocode_cache_time",
            field=models.DateTimeField(
                default=datetime.datetime(2018, 11, 24, 20, 37, 23, 598978, tzinfo=utc)
            ),
        ),
    ]
