# Generated by Django 3.1.3 on 2020-11-16 23:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0006_auto_20201116_1248"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute", models.CharField(max_length=250)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="place",
            name="reverse_geocode_cache_time",
            field=models.DateTimeField(
                default=datetime.datetime(2018, 11, 27, 23, 27, 43, 99716, tzinfo=utc)
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="attributes",
            field=models.ManyToManyField(to="walks.PlaceAttribute"),
        ),
    ]
