# Generated by Django 3.1.3 on 2020-11-17 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0007_auto_20201116_2327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="attributes",
            field=models.ManyToManyField(blank=True, to="walks.PlaceAttribute"),
        ),
        migrations.AlterField(
            model_name="place",
            name="reverse_geocode_cache_time",
            field=models.DateTimeField(
                default=datetime.datetime(2018, 11, 28, 9, 31, 41, 824907, tzinfo=utc)
            ),
        ),
    ]
