# Generated by Django 3.1.3 on 2020-11-17 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0008_auto_20201117_0931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="reverse_geocode_cache_time",
            field=models.DateTimeField(
                default=datetime.datetime(2018, 11, 28, 12, 2, 45, 398321, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="walk",
            name="start_location",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="walks.place",
            ),
        ),
    ]
