# Generated by Django 3.1.3 on 2020-11-18 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0009_auto_20201117_1202"),
    ]

    operations = [
        migrations.AddField(
            model_name="walk",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="walk",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="walk",
            name="walk_length",
            field=models.FloatField(
                default=0, help_text="The length of the walk in miles"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="reverse_geocode_cache_time",
            field=models.DateTimeField(
                default=datetime.datetime(2018, 11, 29, 10, 45, 43, 236997, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="placeattribute",
            name="attribute",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
