# Generated by Django 3.1.3 on 2020-11-18 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0010_auto_20201118_1045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="reverse_geocode_cache_time",
            field=models.DateTimeField(
                default=datetime.datetime(2018, 11, 29, 12, 56, 5, 825685, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="walk",
            name="start_location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="walks.place",
            ),
        ),
    ]
