# Generated by Django 3.1.3 on 2020-11-18 13:18

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0011_auto_20201118_1256"),
    ]

    operations = [
        migrations.RenameModel(old_name="PlaceAttribute", new_name="Attribute",),
        migrations.RenameField(model_name="walk", old_name="walk", new_name="route",),
        migrations.RenameField(
            model_name="walk", old_name="walk_length", new_name="route_length",
        ),
        migrations.RemoveField(model_name="walk", name="start_location",),
        migrations.AddField(
            model_name="walk",
            name="attributes",
            field=models.ManyToManyField(blank=True, to="walks.Attribute"),
        ),
        migrations.AddField(
            model_name="walk",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="walk",
            name="continent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="walk",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="walk",
            name="county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="walk",
            name="formatted",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="walk",
            name="geohash",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="walk",
            name="postcode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="walk",
            name="reverse_geocode_cache_time",
            field=models.DateTimeField(
                default=datetime.datetime(2018, 11, 29, 13, 17, 49, 492643, tzinfo=utc)
            ),
        ),
        migrations.AddField(
            model_name="walk",
            name="road",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="walk",
            name="start",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="walk",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="walk",
            name="suburb",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="walk",
            name="what3words",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(name="Place",),
    ]
