# Generated by Django 3.1.3 on 2020-11-19 20:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0012_auto_20201118_1318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walk",
            name="reverse_geocode_cache_time",
            field=models.DateTimeField(
                default=datetime.datetime(2018, 11, 30, 20, 23, 26, 466759, tzinfo=utc)
            ),
        ),
    ]
