# Generated by Django 3.1.3 on 2020-11-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0014_auto_20201120_1047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walk",
            name="reverse_geocode_cache_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
